[platformio]
default_envs = sender

[env]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
  marvinroger/AsyncMqttClient@^0.9.0
  me-no-dev/ESPAsyncTCP@^1.2.2
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH

[env:sender]
build_src_filter =
  +<sender/>
  -<receiver/>
  -<main.cpp>

[env:receiver]
build_src_filter =
  +<receiver/>
  -<sender/>
  -<main.cpp>
